# Generated by Django 2.2.4 on 2019-09-30 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=12)),
                ('current_season_year', models.IntegerField()),
                ('number_of_teams', models.IntegerField()),
                ('number_of_matchdays', models.IntegerField()),
                ('current_matchday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=12, null=True)),
                ('crest_url', models.CharField(max_length=256)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bets.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'SCHEDULED'), (2, 'FINISHED'), (3, 'PLAYING')], default=1)),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awayTeam', to='bets.Team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='bets.Competition')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeTeam', to='bets.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bet_choice', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('bet_outcome', models.IntegerField(blank=True, choices=[(0, 'LOST'), (1, 'WON'), (2, 'PENDING')], default=2)),
                ('bet_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture', to='bets.Fixture')),
            ],
        ),
    ]
