# Generated by Django 2.2.4 on 2019-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
